#server.servlet.context-path=/helloBoot
#spring.profiles.active=prod
#
#my.name=yangfan
#my.password=hx@5236
#
#debug=false
server:
  port: 8888

spring:
  #\u591A\u73AF\u5883\u914D\u7F6E
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.0.6:3306/a_test
    username: hxcloud
    password: Huaxin@Cloud
    # \u4F7F\u7528druid\u6570\u636E\u6E90
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  freemarker:
    #\u662F\u5426\u7F13\u5B58\u9875\u9762
    cache: false
    #freemarker\u6587\u4EF6\u8DEF\u5F84
    template-loader-path: classpath:/templates

#  mvc:
    #    static-path-pattern: /static/*

mybatis:
  #\u626B\u63CFsql.xml\u6587\u4EF6
  mapper-locations: classpath:mapping/*.xml
  #\u81EA\u52A8\u626B\u63CF\u5B9E\u4F53\u7C7B
  type-aliases-package: com.hx.springdemo.entity

